name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    # only execute if this is coming from a push or from a PR from a forked repository
    # otherwise this will get executed twice for PR from internal branches
    if: github.event_name == 'push' || github.event_name == 'pull_request' && (github.event.pull_request.base.repo.full_name != github.event.pull_request.head.repo.full_name)
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - name: Build
        run: |
          if [ "$SONAR_TOKEN" != "" ]
          then
            ./gradlew --parallel spotlessCheck build sonarqube \
            -Dsonar.projectKey=Fraunhofer-AISEC_cpg_neo4j \
            -Dsonar.organization=fraunhofer-aisec \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
          else
            ./gradlew --parallel spotlessCheck nativeImage
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
